export const cryptoSymbols = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  XRP: "XRP",
  LTC: "Litecoin",
  BCH: "Bitcoin Cash",
  EOS: "EOS",
  BNB: "Binance Coin",
  BSV: "Bitcoin SV",
  XLM: "Stellar",
  ADA: "Cardano",
  TRX: "TRON",
  XMR: "Monero",
  DASG: "Dash",
  MIOTA: "IOTA",
  ONT: "Ontology",
  ETC: "ETH Classic",
  NEO: "NEO",
  XTZ: "Tezos",
  XEM: "NEM",
  MKR: "Maker"
};
